name: Daily Commit

on:
  schedule:
    - cron: '29 13 * * *'  # Runs daily at 6:47 PM IST (13:17 UTC)
  workflow_dispatch:  # Optional: lets you manually test it

permissions:
  contents: write  # ⬅️ Needed so GitHub can push changes

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file (24f2008883@ds.study.iitm.ac.in)
        run: |
          echo "Last run: $(date -u) - $RANDOM" > last-run.txt

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last-run.txt
          git commit -m "Automated daily update: $(date -u)"
          git push
